---
- name: Create partitions gpt & mbr through loops and variables. ( variable inside playbook only )
  hosts: localhost
  vars:
    parts:
    - number: 1
      start: "0%"
      end: 1GiB
      name: part1
    - number: 2
      start: 1GiB
      end: 2GiB
      name: part2
    - number: 3
      start: 2GiB
      end: 3GiB
      name: part3
  tasks: 
    - name: create partitions GPT with loop used parted module 
      parted:
        device: /dev/nvme0n2
        number: "{{ item.number }}"
        part_start: "{{ item.start }}"
        part_end: "{{ item.end }}"
        label: gpt
        name: "{{ item.name }}"
        state: present
      loop: "{{ parts }}"

    - name: create partitions MBR with loop used parted module
      parted:
        device: /dev/nvme0n3
        number: "{{ item.number }}"
        part_start: "{{ item.start }}"
        part_end: "{{ item.end }}"
        label: msdos
        part_type: primary
        state: present
      loop: "{{ parts }}"
